modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="playertemplate"
version="${file.jarVersion}"
displayName="Player Template"
authors="gigaherz"
description='''
Small mod to apply an inventory template to all new players.
'''

[[dependencies.playertemplate]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playertemplate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
