modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"

[[mods]]
modId="playertemplate"
version="${file.jarVersion}"
displayName="Player Template"
authors="gigaherz"
description='''
Small mod to apply an inventory template to all new players.
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.playertemplate]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.0-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playertemplate]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
